export const MATCH_TEAMS = 'MATCH_TEAMS';
export const GET_MATCH_DATA = 'GET_MATCH_DATA';
export const SET_MATCH_DATA = 'SET_MATCH_DATA';
export const ADD_MATCH_DATA = 'ADD_MATCH_DATA';
export const UPDATE_CURR_MATCH_DATA = 'UPDATE_CURR_MATCH_DATA';
export const SAVE_CURR_MATCH_DATA = 'SAVE_MATCH_DATA';