export const GETDATA = "GETDATA";
export const SETDATA = "SETDATA";
// export const TOKEN="TOKEN";
export const LOGIN = "LOGIN";
export const ADDTEAM = "ADDTEAM";
export const SETTEAMDATA = "SETTEAMDATA";
export const SCOREZERO="SCOREZERO"
export const SCOREONE="SCOREONE"
export const SCORETWO="SCORETWO"
export const SCORETHREE="SCORETHREE"
export const SCOREFOUR="SCOREFOUR"
export const SCORESIX="SCORESIX"
export const WIDEBALL="WIDEBALL"
export const WICKET="WICKET"
export const DEADBALL="DEADBALL"
export const OUT="OUT"
export const NOBALL="NOBALL"
export const REMOVE="REMOVE"
